FROM openjdk:8
ADD target/RegistrationPeople-0.1-RELEASE.jar app.jar
RUN bash -c 'touch /app.jar'
EXPOSE 8084
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=container", "-jar", "app.jar"]